language: node_js
node_js:
 - "node"

cache: npm

before_script:
  - echo "lypoa.com" > CNAME

script: 
  - yarn && yarn build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GH_TOKEN
 local_dir: dist
 on:
   branch: master